from odoo import api, fields, models
from odoo.exceptions import AccessError

SCHEMA_VERSION = 1


class StockBarcodeScanLog(models.Model):
    """One row per scanner action. Append-only; the schema is versioned so an
    external reconciliation service can consume it (read via JSON-RPC/XML-RPC)."""

    _name = "stock.barcode.scan.log"
    _description = "Barcode scan log"
    _order = "id desc"
    _log_access = True

    schema_version = fields.Integer(default=SCHEMA_VERSION, readonly=True)
    user_id = fields.Many2one("res.users", "User", required=True, index=True, readonly=True,
                              default=lambda self: self.env.uid)
    device = fields.Char(readonly=True, help="Device identifier sent by the scanner client")
    company_id = fields.Many2one("res.company", required=True, readonly=True, index=True,
                                 default=lambda self: self.env.company)
    operation = fields.Selection([
        ("scan", "Scan"),
        ("set_qty", "Quantity typed"),
        ("add_product", "Product added manually"),
        ("pack", "Put in pack"),
        ("validate", "Validate"),
        ("inv_scan", "Count scan"),
        ("inv_set_qty", "Count typed"),
        ("inv_clear", "Count removed"),
        ("inv_zero", "Uncounted set to zero"),
        ("inv_apply", "Counts applied"),
        ("home_scan", "Main menu scan"),
    ], required=True, readonly=True, index=True)
    barcode = fields.Char(readonly=True, index=True)
    resolved_type = fields.Char("Recognized as", readonly=True)
    level = fields.Selection([("success", "OK"), ("info", "Info"), ("warning", "Warning"), ("danger", "Error")],
                             readonly=True, index=True)
    message = fields.Char(readonly=True)
    picking_id = fields.Many2one("stock.picking", readonly=True, index=True, ondelete="set null")
    batch_id = fields.Many2one("stock.picking.batch", readonly=True, index=True, ondelete="set null")
    picking_type_id = fields.Many2one("stock.picking.type", readonly=True, ondelete="set null")
    product_id = fields.Many2one("product.product", readonly=True, index=True, ondelete="set null")
    lot_name = fields.Char("Lot/Serial", readonly=True)
    location_id = fields.Many2one("stock.location", readonly=True, ondelete="set null")
    package_name = fields.Char(readonly=True)
    quantity = fields.Float(digits="Product Unit", readonly=True, help="Quantity added or set by this action")
    old_quantity = fields.Float(digits="Product Unit", readonly=True)
    move_line_id = fields.Integer(readonly=True)
    client_uuid = fields.Char("Client scan id", readonly=True, copy=False,
                              help="Unique id generated by the scanner for each scan; a scan re-sent after a "
                                   "network failure is recognized and not counted twice.")

    def init(self):
        self.env.cr.execute("""
            CREATE UNIQUE INDEX IF NOT EXISTS stock_barcode_scan_log_client_uuid_uniq
            ON stock_barcode_scan_log (client_uuid) WHERE client_uuid IS NOT NULL
        """)
    quant_id = fields.Integer(readonly=True)

    @api.model
    def _bc_seen(self, client_uuid):
        return bool(client_uuid) and bool(self.sudo().search_count([("client_uuid", "=", client_uuid)], limit=1))

    @api.model
    def _bc_write(self, operation, **vals):
        vals.setdefault("device", (self.env.context.get("bc_device") or "")[:120])
        meta = self.env.context.get("bc_event") or {}
        if meta.get("uuid") and operation in ("scan", "inv_scan") and "client_uuid" not in vals:
            vals["client_uuid"] = meta["uuid"]
        vals["operation"] = operation
        vals["user_id"] = self.env.uid
        vals["company_id"] = self.env.company.id
        if vals.get("message"):
            vals["message"] = str(vals["message"])[:500]
        return self.sudo().create(vals)

    def write(self, vals):
        # append-only
        if not self.env.su:
            raise AccessError(self.env._("Scan logs cannot be modified."))
        return super().write(vals)
